personalit/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import PersonalityResource
from . import views

personality_resource = PersonalityResource()

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('personalities/', include('personalities.urls')),
    path('api/', include(personality_resource.urls))
]

personalities/urls.py
from django.urls import path
from . import views
# personalities/
# personalities/1
app_name = 'personality'

urlpatterns = [
    path('', views.index, name='index'),
    path('<personality_mbtitype>', views.detail, name='detail')
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from personalities.models import Personality


class PersonalityResource(ModelResource):
    class Meta:
        queryset = Personality.objects.all()
        resource_name = 'personalities'

personalities/models.py
from django.db import models
from django.utils import timezone


class Classification(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Personality(models.Model):
    mbtitype = models.CharField(max_length=4)
    name = models.CharField(max_length=255)
    description = models.TextField()
    classification = models.ForeignKey(
        Classification, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

personalit/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

personalities/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Personality

# Create your views here.


def index(request):
    # select * from personalities_personality
    personalities = Personality.objects.all()
    # output = ', '.join([p.name for p in personalities])
    # WHERE
    # .objects.filter(personality=)
    # .objects.get(id=1)
    return render(request, 'personalities/index.html', {'personalities': personalities})


def detail(request, personality_mbtitype):
    personality = get_object_or_404(Personality, mbtitype=personality_mbtitype)
    return render(request, 'personalities/detail.html', {'personality': personality})

    # try:
    #     personality = Personality.objects.get(mbtitype=personality_mbtitype)
    #     return render(request, 'personalities/detail.html', {'personality': personality})
    # except Personality.DoesNotExist:
    #     raise Http404()

personalities/templates/personalities/detail.html
{% extends 'base.html' %}

{% block content %}
    <dl>
        <dd>name</dd>
        <dl>{{personality.name}}</dl>
        <dd>type</dd>
        <dl>{{personality.mbtitype}}</dl>
        <dd>description</dd>
        <dl>{{personality.description}}</dl>
    </dl>

{% endblock %}

personalities/templates/personalities/index.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Type Chars</th>
            <th>Name</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        {% for personality in personalities %}
        <tr>
            <td>
            <a href="{% url 'personality:detail' personality.mbtitype %}">
                {{ personality.mbtitype }}
            </a>   
            </td>
            <td>{{ personality.name }}</td>
            <td>{{ personality.description }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Personalit</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'personality:index'%}">Personalit</a>
        </div>
      </nav>
      <main class="container">
      {% block content %}
      {% endblock %}
      </main>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'personality:index'%}">Welcome!! Click me to start!</a>
{% endblock %}